name: Test and Deploy whatsapp-server

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Do you want to deploy?"
        required: true
        default: "false"
        type: choice
        options:
          - true
          - false


jobs:
  test-whatsapp-server:
    runs-on: ubuntu-latest

    env:
        DOCKERFILE_DIR: deployment
        AWS_APPLICATION_NAME: whatsapp-server
        ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}
        DOT_ENV_PATH: .env

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create .env file
        run: |
          echo "WHATSAPP_ACCESS_TOKEN=${{ secrets.WHATSAPP_ACCESS_TOKEN }}" >> $DOT_ENV_PATH
          echo "WHATSAPP_VERIFY_TOKEN=${{ secrets.WHATSAPP_VERIFY_TOKEN }}" >> $DOT_ENV_PATH
          echo "WHATSAPP_SERVER_NUMBER_ID=${{ secrets.WHATSAPP_SERVER_NUMBER_ID }}" >> $DOT_ENV_PATH

      - name: Build Docker image
        run: |
          docker build -f $DOCKERFILE_DIR/Dockerfile \
            -t $ECR_REPO_URL:latest .


  deploy-whatsapp-server:
    runs-on: ubuntu-latest
    needs: test-whatsapp-server
    if: github.event.inputs.deploy == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true