name: Test and Deploy whatsapp-server

on:
  workflow_dispatch:
    inputs:
      deploy:
        description: "Do you want to deploy?"
        required: true
        default: "false"
        type: choice
        options:
          - true
          - false


jobs:
  test-whatsapp-server:
    runs-on: ubuntu-latest

    env:
        DOCKERFILE_DIR: deployment
        ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}
        DOT_ENV_PATH: .env

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create .env file
        run: |
          echo "WHATSAPP_ACCESS_TOKEN=${{ secrets.WHATSAPP_ACCESS_TOKEN }}" >> $DOT_ENV_PATH
          echo "WHATSAPP_VERIFY_TOKEN=${{ secrets.WHATSAPP_VERIFY_TOKEN }}" >> $DOT_ENV_PATH
          echo "WHATSAPP_SERVER_NUMBER_ID=${{ secrets.WHATSAPP_SERVER_NUMBER_ID }}" >> $DOT_ENV_PATH

      - name: Build Docker image
        run: |
          docker build -f $DOCKERFILE_DIR/Dockerfile \
            -t $ECR_REPO_URL:latest .

      - name: Run pytest tests inside Docker container
        run: |
          CONTAINER_ID=$(docker run -d -v $PWD:/results $ECR_REPO_URL:latest)
          docker exec $CONTAINER_ID python3 -m pytest -v -s /whatsapp-server-template/tests/ --junitxml=/results/test-results-1.xml
          TEST_RESULT=$?
          docker stop $CONTAINER_ID
          exit $TEST_RESULT

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-1
          path: test-results-1.xml

      - name: Fail job if tests failed
        if: steps.run-tests.outcome == 'failure'
        run: |
          echo "Tests failed"
          exit 1


  deploy-whatsapp-server:
    runs-on: ubuntu-latest
    needs: test-whatsapp-server
    if: github.event.inputs.deploy == 'true'

    env:
        DOCKERFILE_DIR: deployment
        AWS_APPLICATION_NAME: whatsapp-server-template
        ECR_REPO_URL: ${{ secrets.ECR_REPO_URL }}
        AWS_PUBLIC_S3_BUCKET_NAME: ${{ secrets.AWS_PUBLIC_S3_BUCKET_NAME }}
        AWS_PUBLIC_S3_FOLDER_URI: ${{ secrets.AWS_PUBLIC_S3_FOLDER_URI }}
        AWS_PUBLIC_S3_KEY: ${{ secrets.AWS_PUBLIC_S3_KEY }}
        DOT_ENV_PATH: .env

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create .env file
        run: |
          echo "WHATSAPP_ACCESS_TOKEN=${{ secrets.WHATSAPP_ACCESS_TOKEN }}" >> $DOT_ENV_PATH
          echo "WHATSAPP_VERIFY_TOKEN=${{ secrets.WHATSAPP_VERIFY_TOKEN }}" >> $DOT_ENV_PATH
          echo "WHATSAPP_SERVER_NUMBER_ID=${{ secrets.WHATSAPP_SERVER_NUMBER_ID }}" >> $DOT_ENV_PATH

      - name: Build Docker image
        run: |
          docker build -f $DOCKERFILE_DIR/Dockerfile \
            -t $ECR_REPO_URL:latest .

      - name: Run pytest tests inside Docker container
        run: |
          CONTAINER_ID=$(docker run -d -v $PWD:/results $ECR_REPO_URL:latest)
          docker exec $CONTAINER_ID python3 -m pytest -v -s /whatsapp-server-template/tests/ --junitxml=/results/test-results-2.xml
          TEST_RESULT=$?
          docker stop $CONTAINER_ID
          exit $TEST_RESULT

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-2
          path: test-results-2.xml

      - name: Fail job if tests failed
        if: steps.run-tests.outcome == 'failure'
        run: |
          echo "Tests failed"
          exit 1

      - name: Push Docker image to ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin $ECR_REPO_URL
          docker push $ECR_REPO_URL:latest

      - name: Upload Dockerrun.aws.json to S3
        run: |
          cd $DOCKERFILE_DIR
          sed -i -e "s|ECR_REPO_URL|${ECR_REPO_URL}|g" Dockerrun.aws.json
          zip $AWS_APPLICATION_NAME.zip Dockerrun.aws.json
          aws s3 cp $AWS_APPLICATION_NAME.zip $AWS_PUBLIC_S3_FOLDER_URI$AWS_APPLICATION_NAME.zip

      - name: Deploy app
        run: |
          pip3 install --upgrade pip
          pip3 install awsebcli
          TIMESTAMP=$(date +'%Y-%m-%d_%H-%M-%S')
          aws elasticbeanstalk create-application-version \
            --application-name $AWS_APPLICATION_NAME \
            --region ${{ secrets.AWS_REGION }} \
            --version-label $TIMESTAMP \
            --source-bundle S3Bucket="$AWS_PUBLIC_S3_BUCKET_NAME",S3Key="$AWS_PUBLIC_S3_KEY/$AWS_APPLICATION_NAME.zip"
          eb init -p Docker --region ${{ secrets.AWS_REGION }} $AWS_APPLICATION_NAME
          eb deploy $AWS_APPLICATION_NAME --version $TIMESTAMP --timeout 30
